language: node_js
node_js: 14
services: mongodb
cache:
  directories: backend/node_modules
before_install: 
  - cd backend
  - cp .env.sample .env
install: npm ci
before_script: sleep 5
script: npm test
