# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [master]
    paths:
      - "backend/**"
  pull_request:
    branches: [master]
    paths:
      - "backend/**"

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      working-directory: ./backend

    services:
      mongodb:
        image: mongo
        ports:
          - 27017:27017

    steps:
      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "14.x"

      - uses: mattallty/jest-github-action@v1.0.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          test-command: "npm run testCoverage"
          changes-only: true
          working-directory: ${{ env.working-directory }}

      - name: setup env
        working-directory: ${{ env.working-directory }}
        run: cp .env.sample .env

      - name: npm install
        working-directory: ${{ env.working-directory }}
        run: npm install

      - name: npm test
        working-directory: ${{ env.working-directory }}
        run: npm test
