# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  pull_request:
    branches: [master]

jobs:
  test:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    env:
      working-directory: ./backend

    services:
      mongodb:
        image: mongo
        ports:
          - 27017:27017

    steps:
      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "14.x"

      - name: setup env
        working-directory: ${{ env.working-directory }}
        run: cp .env.sample .env

      - name: npm ci
        working-directory: ${{ env.working-directory }}
        run: npm ci

      - name: npm test
        working-directory: ${{ env.working-directory }}
        run: npm test

      - uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./backend/coverage/clover.xml # optional
          name: backend-deploy
          fail_ci_if_error: false # optional
          verbose: true # optional (default = false)
